### ISSUE TITLE
About token files

### ISSUE THREAD

**Issue by dogagunduzalp** [HorizonRobotics/GUMP#2]
Hello,

Thank you for this great work. I couldn't find the files called `training_token_list.txt` and `validation_token_list_256.txt` used by `nuplan_extent/planning/scenario_builder/wod_db/wod_scenario_builder.py` in the repository. I would be very happy if you could guide me on these issues. Thanks!

**Comment by zheningy** [comment]
Thank you for catching that.

These tokens are scenario_name + sdc_track_index. The token list generation has been added in https://github.com/HorizonRobotics/GUMP/commit/bfec7cbfe2d1e8ea0e62374e7577ffcfd96ead1a
