### ISSUE TITLE
What is the subsample ratio for wod training?

### ISSUE THREAD

**Issue by synsin0** [HorizonRobotics/GUMP#4]
Thanks for your great work！ I find the preprocessing sets the subsample ratio to 10000. I find the training tokens have around 480k samples, and if subsampled to 10000, there are only 48 training samples. I wonder which subsample ratio do you use in training process？

**Comment by Yihanhu** [comment]
For testing purposes, I've set it to 10,000.  I used the entire set for training, which should be set to 1.

**Comment by synsin0** [comment]
Thanks for your answer. By the way, the checkpoint(https://[storage.googleapis.com/93935945854-us-central1-blueprint-config/gptm_wod.ckpt](https://storage.googleapis.com/93935945854-us-central1-blueprint-config/gptm_wod.ckpt) can not be accessed by website. How can I download this checkpoint?

**Comment by Yihanhu** [comment]
> Thanks for your answer. By the way, the checkpoint(https://[storage.googleapis.com/93935945854-us-central1-blueprint-config/gptm_wod.ckpt](https://storage.googleapis.com/93935945854-us-central1-blueprint-config/gptm_wod.ckpt) can not be accessed by website. How can I download this checkpoint?

It's fixed now, please give it another try!

**Comment by synsin0** [comment]
Successfully downloaded! Thanks!
